### PR TITLE
Change "obsolete" to "archived".

### PR DESCRIPTION
**Pull request by dsjen**
Conform to changes in OEP-2.

https://open-edx-proposals.readthedocs.io/en/latest/oep-0002.html

@edx/analytics please review

### CODE REVIEW

**Comment by dsjen** [comment]
@cahrens

**Comment by cahrens** [comment]
👍 Thanks @dsjen. I can't merge this though, since I don't have write access to the repository.

image

**Comment by dsjen** [comment]
Ugh!  I don't have write access to this either it turns out.  @brianhw do you have access?

**Comment by brianhw** [comment]
Nope, not I either....  @mulby?

**Comment by nedbat** [comment]
(Someone let me know if I shouldn't have clicked the button...)

**Pull request merged**
