### PR TITLE
Remove unused flup dependency

### PR DESCRIPTION
**Pull request by collinanderson**
Not sure why it's there.

### CODE REVIEW

**Comment by rocha** [comment]
@clintonb as the readme says, this repository contains an early prototype. We won't be continuing development, but anyone interested is free to fork it.

**Comment by sarina** [comment]
@rocha I wonder if it makes sense to more clearly and explicitly say that in the very, very top of the repo's README.

**Comment by rocha** [comment]
@sarina good idea. I added a clarification.

**Comment by collinanderson** [comment]
maybe the repo description could be more clear too?

**Comment by rocha** [comment]
@collinanderson I updated the description. Does it help?

**Comment by collinanderson** [comment]
perfect. thanks

**Pull request closed without merging**
